[package]
org = "zero_hack"
name = "svg_parser"
version = "0.5.3"
distribution = "2201.7.1"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "zerohack"
name = "github"
version = "0.7.0"