[package]
org = "zero_hack"
name = "svg_parser"
version = "0.6.2"
distribution = "2201.7.1"

[build-options]
observabilityIncluded = true
cloud = "docker"

[[dependency]]
org = "zerohack"
name = "github"
version = "0.7.0"
