name: Test pull request

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out ✊
        uses: actions/checkout@v3

      - name: Setup Ballerina 🪤
        uses: ballerina-platform/setup-ballerina@v1
        with:
          version: 2201.7.1

      - name: Ballerina Test 🛡
        run: bal test --test-report --code-coverage --coverage-format=xml

      - name: Upload coverage reports to Codecov 📄
        uses: codecov/codecov-action@v3
        with:
          files: ./target/report/svg_parser/coverage-report.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  test-success:
    if: ${{ success() }}
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get Repository Name 🍺
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_ENV
      - name: Success Notify to Slack ✅
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: [${{ env.REPOSITORY_NAME }}] Test Success✅
          SLACK_USERNAME: announcer
          SLACK_WEBHOOK: ${{ secrets.SLACK_HOOK_GHA_CI_URL }}

  test-failed:
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get Repository Name 🍺
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}" >> $GITHUB_ENV
      - name: Failed Notify to Slack ❌
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: [${{ env.REPOSITORY_NAME }}] Test Failed❌
          SLACK_USERNAME: announcer
          SLACK_WEBHOOK: ${{ secrets.SLACK_HOOK_GHA_CI_URL }}
