name: Test pull request

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out ✊
        uses: actions/checkout@v3

      - name: Ballerina Test 🛡
        uses: ballerina-platform/ballerina-action/@2201.7.1
        with:
          args: test --test-report --code-coverage --coverage-format=xml
      - name: Upload coverage reports to Codecov 📄
        uses: codecov/codecov-action@v3
        with:
          files: ./target/report/svg_parser/coverage-report.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
